### ISSUE TITLE
Browser <script> tag friendly build

### ISSUE THREAD

**Issue by foxdonut** [flintinatux/tinyfunk#9]
Hi @flintinatux 

Thank you for `tinyfunk`, nice alternative lightweight library for FP goodness.

Any chance of providing a <script> tag friendly build?

Also, if you do that, you could also add `"unpkg": "path/to/build.js"` to `package.json`, then one could add tinyfunk simply with `<script src="https://unpkg.com/tinyfunk"></script>`.

Thanks!

**Comment by flintinatux** [comment]
That's a great idea.  I'll add that to my list!

**Comment by foxdonut** [comment]
@flintinatux One could then experiment with `tinyfunk` simply with [http://flems.io/tinyfunk](http://flems.io/tinyfunk).

Thanks!

**Comment by flintinatux** [comment]
Thanks for your patience on this, @foxdonut.  I've been busy working on the v2 of [`paperplane`](https://github.com/articulate/paperplane), but since that's finished, I wanted to get back on your request.  I appreciate you taking an interesting and participating in this project!

**Comment by foxdonut** [comment]
Fantastic, @flintinatux -- by the way, `paperplane` ROCKS, I'll be using it for my next node app. Thank you for all of your excellent work!
